### PR TITLE
Handle chain information in explicit form in invoices

### LINKED ISSUE #103: Network not set on invoice
Despite setting the network argument, we get still invoices like this:
`rgb:Cbw1h3zbHgRhA6sxb4FS3Z7GTpdj9MLb7Do88qh5TUH1/RGB20/1+utxob02FKN7XB4N5LWc1d6cXfkByZ8d1jB4BZhee1vdU7MwffTtLkiK3`
When parsed, it lacks the network argument.
This will be helpful for users to better verify and troubleshoot their transfers.

### PR DESCRIPTION
**Pull request by dr-orlovsky**
This is a breaking change since inside the invoice structure we make `chain` non-optional; plus we add new error cases and make `set_chain` return `Result`. Thus I am making this PR against `v11` branch.

Closes #103

### CODE REVIEW

**Review by cryptoquick — APPROVED** [review]
ACK
Very comprehensive tests cases. Looks good.
I also agree, 0.11 is a good place to put this.

**Comment by fedsten** [comment]
Any reason why it is non-optional instead of optional as discussed in #103?

**Comment by dr-orlovsky** [comment]
@fedsten the parameter is optional as was discussed, thus the invoice string is backwards-compatible. However, for each given invoice we always know which network it belongs to (since we are defaulting to mainnet as discussed), thus we must have a non-optional field.

**Comment by fedsten** [comment]
Got it,  for clarifying.

**Comment by dr-orlovsky** [comment]
In other words, a wallet will always know and be sure to which network a given invoice belongs. If the invoice has conflicting network information (like an address network doesn't match the network provided in a parameter) it will error during the parse procedure. But each parsed invoice always knows which network it is valid for,

**Review by zoedberg — CHANGES_REQUESTED** [review]
I'm trying to review the PR but executing tests I'm encountering some issues.
It seems that the `LoadError` is defined only when the `fs` feature is active but then used in other parts of code available without that feature. Moreover, if I run tests activating all features, I receive the following error:
```
error[E0599]: no method named `assume_checked` found for struct `bp::Address` in the current scope
   --> invoice/src/parse.rs:454:14
    |
452 |           let addr_bc = Address::from_str("bc1qpws79r3ea4yy2ujsahwrmy2gutdj8w5whnhket")
    |  _______________________-
453 | |             .unwrap()
454 | |             .assume_checked();
    | |             -^^^^^^^^^^^^^^ method not found in `Address`
    | |_____________|
    | 

error[E0599]: no method named `assume_checked` found for struct `bp::Address` in the current scope
   --> invoice/src/parse.rs:457:14
    |
455 |           let addr_tc = Address::from_str("mxVFsFW5N4mu1HPkxPttorvocvzeZ7KZyk")
    |  _______________________-
456 | |             .unwrap()
457 | |             .assume_checked();
    | |             -^^^^^^^^^^^^^^ method not found in `Address`
    | |_____________|
    | 

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rgb-invoice` (lib test) due to 2 previous errors
```

**Comment by dr-orlovsky** [comment]
@zoedberg wait, we do not have CI set up for this repo? Oh, I'll fix it.

I did this PR originally against v0.10 branch which was used rust-bitcoin v0.30. Then I understood it's breaking, so moved to v0.11, which doesn't depend on rust-bitcoin at all and have a different `Address` type (from `bp-std`) with different API. Thus the issue. Will fix.

**Comment by dr-orlovsky** [comment]
Closing in favor of solution from https://github.com/RGB-WG/rgb-std/pull/118

**Pull request closed without merging**
