### PR TITLE
fix: invoice baid64 encode & decode for P2TR address

### PR DESCRIPTION
**Pull request by Crayon-Shin-chan-1024**
#212

### CODE REVIEW

**Comment by eauxxs** [comment]
see #210, 你只修复了p2tr, 并且修复的方式不太对。Pay2Vout编码方案是第一个byte存储CloseMethod, 第二个byte存储地址类型，然后剩余的内容就是scriptbuf去掉前缀和后缀的hash bytes。主要错误的地方是在to_baid64_payload，所以主要更改的也应该是这个。
你把数组长度从35改成37，他也不可能接受的，35已经冗余了。

**Review by dr-orlovsky — CHANGES_REQUESTED** [review]
LGTM but please do not change formatting of random unrelated parts

**Comment by crayon-xiao-xin** [comment]
> LGTM but please do not change formatting of random unrelated parts

sorry, i'm forgot the fmt, i had force pushed that restore the fmt

**Comment by bitlightlabs-dev** [comment]
Fixed for rgb shell command:
```
rgb -d .bob invoice $RGB20_CONTRACT RGB20Fixed 2000 --address-based 
```

**Review by dr-orlovsky — COMMENTED** [review]
Please see my comment in https://github.com/RGB-WG/rgb-std/issues/212#issuecomment-2167567148

We also certainly do not need 37 bytes

**Comment by crayon-xiao-xin** [comment]
> Please see my comment in [#212 (comment)](https://github.com/RGB-WG/rgb-std/issues/212#issuecomment-2167567148)
> 
> We also certainly do not need 37 bytes

yep, i have fixed it, we just encode the address payload, so we just need 34 bytes to hold the encoded bytes

**Review by dr-orlovsky — APPROVED** [review]
ACK 60e86ca5ea93f5479e3bcc16525e184172b31cb0

**Pull request merged**
