### PR TITLE
Move remainder of rust-rgb20 into rgb-std

### PR DESCRIPTION
**Pull request by cryptoquick**
So, watching you build RGB is like watching Leonardo Da Vinci paint the Mona Lisa. And I feel like this, opening this malformed PR:
Botched Ecce Homo

I was merely inspired by your original deprecated comment (before Wednesday's call), but alas, it's beyond my skill, and not terribly necessary, either.

That said, if you think there's some value in the work, I'm having trouble with resolving some of the `cargo check` errors.

If you want me to finish it, I could use a few pointers, and I can also squash the commits into a proper commit message.

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
LOL regarding the pic :) No, you are overestimating my abilities.

On the topic: why do you think that having RGB20 in stdlib is a good idea? My point is to separate RGB stdlib and specific schema, such that new schema can be created without changing the stdlib at all - and in the future not even with the rust, but with AluVM/Contractum. If we put schema-specifics into the stdlib we would not be able to do that and will dim the lines of the abstraction and separation of concerns.

**Comment by dr-orlovsky** [comment]
I think now I am getting it: I forgot to remove the deprecation warning from the RGB20 repo. It is undeprecated for at least a month for now and is activelly developed :D

**Comment by cryptoquick** [comment]
Haha, yeah, that's what led me to do this work. It's probably a terrible idea, but I was also distracted by the existence of a `fungible` directory, and the moving of the Blind command. If rust-rgb20 is not to be deprecated, there's no point in finishing this work.

**Comment by dr-orlovsky** [comment]
Sorry, it is my fault of not communicating/indicating properly

**Pull request closed without merging**
