### PR TITLE
collect supplements in issue contract

### PR DESCRIPTION
**Pull request by cymqqqq**
Description:

add collect supplements feature for the `issue_contract`, includes the following Supplement instance:

genesis supplement
iface supplement
iimpl supplement
schema supplement

### CODE REVIEW

**Review by dr-orlovsky — CHANGES_REQUESTED** [review]
You can just do
```
supplements: confined_bset![
   Supplement::new(ContentRef::Schema(schema.schema_id()), schema.developer.clone()),
    ...
]
```

**Comment by cymqqqq** [comment]
Sorry....I always use the `update branch` button, next time I'll try to `git rebase main`.

**Review by dr-orlovsky — CHANGES_REQUESTED** [review]
Sorry, just understood that in this PR instead of gathering supplements from the stash you create some pseudo-supplements out of arbitrary cosnensus data.

Approach NACK. Please either collect supplements from the stash - or close the PR

**Comment by cymqqqq** [comment]
I agree with you, the first idea is to collect supplements from the stash, but the question is: do we have a stash when we issue a contract? (In the `consign` method, yes, there is already a stash so we can collect supplements from the stash.) I just found `ContractBuilder`, and after we finish the contract issue, then initialize a stock(`MemStash`, `MemState`, and `MemIndex`), and then we can import the kit and contract to the stash.

**Comment by dr-orlovsky** [comment]
When you issue contract you need to collect just supplements for interfaces, schema and implementation. There is no "genesis supplement" which can be found in the stash.

You also need to keep in mind that right now there is no supplements which exist - this functionality is there only as a way to add new things in the future.

**Pull request closed without merging**
